# Generated by Django 5.0.4 on 2024-05-05 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Зазначте здібності!', max_length=200, verbose_name='Здібності')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Введіть ім'я!", max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(help_text='Введіть прізвище!', max_length=100, verbose_name='Прізвище')),
                ('date_of_birth', models.DateField(blank=True, help_text='Введіть дату народження!', null=True, verbose_name='Дата народження')),
                ('date_of_enrollment', models.DateField(blank=True, help_text='Введіть дату приєднання до колективу!', null=True, verbose_name='Приєднався до нас')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Зазначте посаду!', max_length=20, verbose_name='Посада')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть статус', max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Введіть коротке ім'я!", max_length=200, verbose_name="Коротке ім'я")),
                ('summary', models.TextField(help_text='Охарактеризуйте працівника!', max_length=1000, verbose_name='Характеристика працівника')),
                ('isbn', models.CharField(help_text='Введіть номер телефону!', max_length=13, verbose_name='Номер телевону!')),
                ('abilities', models.ForeignKey(help_text='Оберіть здібності!', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.abilities', verbose_name='Здібність')),
                ('author', models.ManyToManyField(help_text='Оберіть працівника!', null=True, to='catalog.author', verbose_name='Працівник')),
                ('position', models.ForeignKey(help_text='Оберіть посаду!', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.position', verbose_name='Посада')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(help_text='Введіть ідентифікаційний номер!', max_length=20, null=True, verbose_name='Ідентифікаційний номер')),
                ('passport', models.CharField(help_text='Введіть дані паспорта!', max_length=200, verbose_name='Паспорт')),
                ('due_back', models.DateField(blank=True, help_text='Введіть кінець терміну статусу!', null=True, verbose_name='Дата закінчення статусу')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.employee')),
                ('status', models.ForeignKey(help_text='Змінити статус', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Статус')),
            ],
        ),
    ]
