# Generated by Django 5.0.4 on 2024-05-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='author',
            field=models.ManyToManyField(help_text='Оберіть працівника!', to='catalog.author', verbose_name='Працівник'),
        ),
    ]
