# Generated by Django 5.0.4 on 2024-05-05 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_employee_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='author',
        ),
        migrations.AddField(
            model_name='employee',
            name='abilities',
            field=models.ManyToManyField(help_text='Оберіть здібності!', to='catalog.abilities', verbose_name='Здібність'),
        ),
        migrations.AddField(
            model_name='employee',
            name='author',
            field=models.ForeignKey(help_text='Оберіть працівника!', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.author', verbose_name='Працівник'),
        ),
    ]
